---
name: try golang build

on:
  push:
    branches:
      - dependabot/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: "1.17.6"
      - run: go build .
