---
name: build OCI image

on:
  push:
    branches:
      - "*"
      - "**"
      - "!dependabot/**"
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Set image tag
        run: |
          if [[ "${{ steps.get_version.outputs.version }}" != "" && "${{ steps.get_version.outputs.version }}" != "master" ]]; then
            TAG="${{ steps.get_version.outputs.version }}"
          else
            TAG="dev"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV
      # - name: GitGuardian scan
      #   uses: GitGuardian/gg-shield-action@master
      #   env:
      #     GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
      #     GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
      #     GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
      #     GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      #     GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      - name: create and push an image
        run: >
          buildah unshare bash ./build.sh
          ${{ env.TAG }}
          ${{ secrets.REGISTRY_USERNAME }}
          ${{ secrets.REGISTRY_PASSWORD }}
